language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_0638c91688c9_key -iv $encrypted_0638c91688c9_iv
  -in team/src/main/resources/application.properties.enc -out team/src/main/resources/application.properties -d
